# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-08 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.CharField(default='F', max_length=20),
        ),
    ]
