# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-15 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_student_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rank',
        ),
    ]
