# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_remove_student_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phy', models.FloatField()),
                ('che', models.FloatField()),
                ('bio', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
